name: Keep HF Space Awake

on:
  schedule:
    - cron: '0 */12 * * *'   # every 12 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Space (3 retries)
        run: |
          for i in 1 2 3; do
            curl -fsS -o /dev/null -L 'https://AnshulPrasad-Climate_Change.hf.space' && exit 0
            sleep 15
          done
          echo "All attempts failed" >&2
          exit 1
